#pragma once

#ifndef OFXLIVESET_USE_GRAPHICS
#define OFXLIVESET_USE_GRAPHICS 1
#endif

#ifndef OFXLIVESET_USE_DOTFRAG
#define OFXLIVESET_USE_DOTFRAG 1
#endif

#ifndef OFXLIVESET_USE_AUDIO
#define OFXLIVESET_USE_AUDIO 1
#endif

#ifndef OFXLIVESET_USE_DMX
#define OFXLIVESET_USE_DMX 1
#endif

#ifndef OFXLIVESET_USE_LUA
#define OFXLIVESET_USE_LUA 0
#endif

#ifndef OFXLIVESET_USE_MQTTSYNCHRONISER
#define OFXLIVESET_USE_MQTTSYNCHRONISER 0
#endif